### ISSUE TITLE
Todo before v0.6

### ISSUE THREAD

**Issue by pkofod** [JuliaOpt/Optim.jl#249]
- [x] decide on wether to use `lower` or `x_lower`
- [x] make sure `lower` and `upper` are used for "box constraints" or bounds
- [ ] use proper deprecation where possible in breaking changes
- [x] setup documenter to create a stable and latest version

more?

edit: the last point is ticked off, as this should automatically happen. I just need to edit the readme just before the version is tagged.

**Comment by johnmyleswhite** [comment]
Assuming that `lower` refers to box constraints, can we use whether terminology is used in Tim Holy's branch of Optim?
